# Generated by Django 4.0.4 on 2022-05-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostname', models.CharField(max_length=100, unique=True)),
                ('Management_IP_address', models.CharField(max_length=30)),
                ('Hardware_vendor', models.CharField(max_length=30)),
                ('Hardware_Type', models.CharField(max_length=30)),
                ('Software_version', models.CharField(max_length=30)),
                ('Physical_Address', models.CharField(max_length=500)),
            ],
        ),
    ]
