# Generated by Django 4.0.4 on 2022-05-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routers_Switches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routers',
            name='Roles',
            field=models.CharField(choices=[('access', 'access'), ('distribution', 'distribution'), ('core', 'core'), ('router', 'router')], max_length=100, null=True),
        ),
    ]
