# Generated by Django 4.0.4 on 2022-05-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Routers_Switches', '0002_routers_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Routers',
            new_name='Router',
        ),
    ]
