# Generated by Django 4.0.4 on 2022-05-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routers_Switches', '0005_alter_interface_device_alter_interface_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediate',
            name='Name',
            field=models.ManyToManyField(to='Routers_Switches.interface'),
        ),
    ]
